//
// Generated by JTB 1.3.2
//

package Simly.syntaxtree;

/**
 * Grammar production:
 * f0 -> RelationalLessExpression()
 * f1 -> [ ( ">" | ">=" ) RelationalLessExpression() ]
 */
public class RelationalGreaterExpression implements Node {
   public RelationalLessExpression f0;
   public NodeOptional f1;

   public RelationalGreaterExpression(RelationalLessExpression n0, NodeOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(Simly.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(Simly.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(Simly.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(Simly.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

